// AgentFM verifiable agent mesh — ledger wire envelopes.
//
// See: docs/superpowers/plans/2026-05-16-verifiable-agent-mesh-implementation.md
//      docs/superpowers/specs/2026-05-02-verifiable-mesh-design.md
//
// Wire-format rules every consumer MUST follow:
//   1. All hash / signature / peer-id fields are `bytes`, never `string`,
//      so callers cannot accidentally apply unicode normalisation.
//   2. Signing is done over SHA-256(canonical_bytes), where canonical_bytes
//      is the message marshalled with mutable fields (Signature, WitnessSigs,
//      RekorAnchor) zeroed. See internal/ledger/pb/canonical.go.
//   3. Field numbers 1-7 are the hot path on every entry; do not reuse a
//      reserved range without bumping the package version.
//   4. Receivers MUST reject envelopes where:
//        - score is outside [-1.0, +1.0]
//        - tree_size == 0 (a head must always reference at least one entry)
//        - prev_hash length != 32 (SHA-256 only)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        (unknown)
// source: agentfm/ledger/v1/ledger.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// One unit of feedback.
// Machine-issued (e.g. P3-3 attestation, P3-6 probe grade) or human-issued
// (e.g. P4-3 signed comment). The rater always commits the entry into its
// OWN log, never the subject's.
type Rating struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// libp2p peer ID (multihash bytes) of the rater. Signing identity is
	// derived from this ID's embedded public key.
	RaterPeerId []byte `protobuf:"bytes,1,opt,name=rater_peer_id,json=raterPeerId,proto3" json:"rater_peer_id,omitempty"`
	// libp2p peer ID of the rated peer.
	SubjectPeerId []byte `protobuf:"bytes,2,opt,name=subject_peer_id,json=subjectPeerId,proto3" json:"subject_peer_id,omitempty"`
	// Free-text dimension; reserved values: "honesty", "latency",
	// "availability", "quality". Unknown dimensions are accepted but ignored
	// by P3-7's reputation matcher.
	Dimension string `protobuf:"bytes,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	// Score in [-1.0, +1.0]. Receivers MUST reject out-of-range envelopes.
	Score float64 `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	// Free-text correlation handle: task_id, probe_round_id, attestation_id.
	// Used by the UI to link a rating back to its evidence.
	Context string `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	// Wall-clock at the moment of issuance, nanoseconds since Unix epoch.
	TimestampUnixNs int64 `protobuf:"varint,6,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	// SHA-256 of the prior entry in the rater's log. Exactly 32 bytes.
	// For the very first entry in a log, this is 32 zero bytes.
	PrevHash []byte `protobuf:"bytes,7,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	// Ed25519 signature over SHA-256(canonical_bytes), where canonical_bytes
	// is this message marshalled with `signature` zeroed.
	Signature     []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rating) Reset() {
	*x = Rating{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rating) ProtoMessage() {}

func (x *Rating) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rating.ProtoReflect.Descriptor instead.
func (*Rating) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Rating) GetRaterPeerId() []byte {
	if x != nil {
		return x.RaterPeerId
	}
	return nil
}

func (x *Rating) GetSubjectPeerId() []byte {
	if x != nil {
		return x.SubjectPeerId
	}
	return nil
}

func (x *Rating) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *Rating) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Rating) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Rating) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

func (x *Rating) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Rating) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Free-text review. The body is content-addressed and stored as a separate
// blob (P4-1) so the Merkle tree stays cheap; only the CID is hashed.
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RaterPeerId   []byte                 `protobuf:"bytes,1,opt,name=rater_peer_id,json=raterPeerId,proto3" json:"rater_peer_id,omitempty"`
	SubjectPeerId []byte                 `protobuf:"bytes,2,opt,name=subject_peer_id,json=subjectPeerId,proto3" json:"subject_peer_id,omitempty"`
	// Multihash CID of the comment body (sha2-256 of the text bytes).
	// The body is fetched on demand via /agentfm/comment-fetch/1.0.0.
	TextCid []byte `protobuf:"bytes,3,opt,name=text_cid,json=textCid,proto3" json:"text_cid,omitempty"`
	// ISO 639-1 language tag of the body, e.g. "en", "ja".
	Language string `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	// Optional: hash of the Rating entry this comment elaborates on.
	// 32 bytes if present; 0 bytes if comment stands alone.
	AttachedRating  []byte `protobuf:"bytes,5,opt,name=attached_rating,json=attachedRating,proto3" json:"attached_rating,omitempty"`
	TimestampUnixNs int64  `protobuf:"varint,6,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	// SHA-256 of the prior entry in the rater's log. Exactly 32 bytes.
	PrevHash []byte `protobuf:"bytes,7,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	// Ed25519 signature over SHA-256(canonical_bytes).
	Signature     []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *Comment) GetRaterPeerId() []byte {
	if x != nil {
		return x.RaterPeerId
	}
	return nil
}

func (x *Comment) GetSubjectPeerId() []byte {
	if x != nil {
		return x.SubjectPeerId
	}
	return nil
}

func (x *Comment) GetTextCid() []byte {
	if x != nil {
		return x.TextCid
	}
	return nil
}

func (x *Comment) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Comment) GetAttachedRating() []byte {
	if x != nil {
		return x.AttachedRating
	}
	return nil
}

func (x *Comment) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

func (x *Comment) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Comment) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Witness co-signature on a LogHead. M-of-N collected on each new head;
// see P2-2 / P2-4.
type WitnessSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WitnessPeerId []byte                 `protobuf:"bytes,1,opt,name=witness_peer_id,json=witnessPeerId,proto3" json:"witness_peer_id,omitempty"`
	// Ed25519 signature over the LogHead bytes with WitnessSigs and
	// RekorAnchor fields zeroed (so all witnesses sign the same bytes
	// regardless of arrival order).
	Signature     []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WitnessSig) Reset() {
	*x = WitnessSig{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WitnessSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WitnessSig) ProtoMessage() {}

func (x *WitnessSig) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WitnessSig.ProtoReflect.Descriptor instead.
func (*WitnessSig) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *WitnessSig) GetWitnessPeerId() []byte {
	if x != nil {
		return x.WitnessPeerId
	}
	return nil
}

func (x *WitnessSig) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Snapshot of a peer's log at a point in time. Heads are gossiped
// independently of entries to support catch-up after restart.
type LogHead struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	PeerId []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// Number of entries committed at the time this head was signed. MUST be
	// monotonically non-decreasing for a given peer_id (P2-2 equivocation
	// check enforces strict growth via consistency proofs).
	TreeSize uint64 `protobuf:"varint,2,opt,name=tree_size,json=treeSize,proto3" json:"tree_size,omitempty"`
	// RFC 6962 Merkle root. Exactly 32 bytes.
	RootHash        []byte `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	TimestampUnixNs int64  `protobuf:"varint,4,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	// Peer's own Ed25519 signature over SHA-256(canonical_bytes) with
	// signature, witness_sigs, and rekor_anchor zeroed.
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// Collected M-of-N witness co-signatures; see P2-4.
	WitnessSigs []*WitnessSig `protobuf:"bytes,6,rep,name=witness_sigs,json=witnessSigs,proto3" json:"witness_sigs,omitempty"`
	// Optional Sigstore Rekor entry UUID; populated only when this head was
	// anchored via --rekor-anchor (P5-3).
	RekorAnchor   string `protobuf:"bytes,7,opt,name=rekor_anchor,json=rekorAnchor,proto3" json:"rekor_anchor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogHead) Reset() {
	*x = LogHead{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogHead) ProtoMessage() {}

func (x *LogHead) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogHead.ProtoReflect.Descriptor instead.
func (*LogHead) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *LogHead) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *LogHead) GetTreeSize() uint64 {
	if x != nil {
		return x.TreeSize
	}
	return 0
}

func (x *LogHead) GetRootHash() []byte {
	if x != nil {
		return x.RootHash
	}
	return nil
}

func (x *LogHead) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

func (x *LogHead) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *LogHead) GetWitnessSigs() []*WitnessSig {
	if x != nil {
		return x.WitnessSigs
	}
	return nil
}

func (x *LogHead) GetRekorAnchor() string {
	if x != nil {
		return x.RekorAnchor
	}
	return ""
}

// Proof that a specific entry sits at a known position in a peer's log
// under a specific signed head.
type InclusionProof struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entry being proven. Exactly one of `rating` or `comment` is set.
	//
	// Types that are valid to be assigned to Entry:
	//
	//	*InclusionProof_Rating
	//	*InclusionProof_Comment
	Entry isInclusionProof_Entry `protobuf_oneof:"entry"`
	// Zero-based index of this entry in the log.
	Position uint64 `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	// RFC 6962 audit path: sibling hashes from the leaf up to the root.
	AuditPath [][]byte `protobuf:"bytes,4,rep,name=audit_path,json=auditPath,proto3" json:"audit_path,omitempty"`
	// The signed head this proof is verified against. Verifier MUST
	// re-derive the root from leaf + audit_path and compare to log_head.root_hash.
	LogHead       *LogHead `protobuf:"bytes,5,opt,name=log_head,json=logHead,proto3" json:"log_head,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InclusionProof) Reset() {
	*x = InclusionProof{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InclusionProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InclusionProof) ProtoMessage() {}

func (x *InclusionProof) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InclusionProof.ProtoReflect.Descriptor instead.
func (*InclusionProof) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *InclusionProof) GetEntry() isInclusionProof_Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *InclusionProof) GetRating() *Rating {
	if x != nil {
		if x, ok := x.Entry.(*InclusionProof_Rating); ok {
			return x.Rating
		}
	}
	return nil
}

func (x *InclusionProof) GetComment() *Comment {
	if x != nil {
		if x, ok := x.Entry.(*InclusionProof_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

func (x *InclusionProof) GetPosition() uint64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *InclusionProof) GetAuditPath() [][]byte {
	if x != nil {
		return x.AuditPath
	}
	return nil
}

func (x *InclusionProof) GetLogHead() *LogHead {
	if x != nil {
		return x.LogHead
	}
	return nil
}

type isInclusionProof_Entry interface {
	isInclusionProof_Entry()
}

type InclusionProof_Rating struct {
	Rating *Rating `protobuf:"bytes,1,opt,name=rating,proto3,oneof"`
}

type InclusionProof_Comment struct {
	Comment *Comment `protobuf:"bytes,2,opt,name=comment,proto3,oneof"`
}

func (*InclusionProof_Rating) isInclusionProof_Entry() {}

func (*InclusionProof_Comment) isInclusionProof_Entry() {}

// Public alert raised when a witness sees two LogHeads at the same or
// overlapping tree_size that do NOT mutually-extend (i.e. the peer has
// shown forked histories). Triggers permanent equivocator marker
// downstream (P2-3 / P3-7). Anyone can verify by checking witness_signature
// against witness_peer_id's public key.
type EquivocationAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        []byte                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	HeadA         *LogHead               `protobuf:"bytes,2,opt,name=head_a,json=headA,proto3" json:"head_a,omitempty"`
	HeadB         *LogHead               `protobuf:"bytes,3,opt,name=head_b,json=headB,proto3" json:"head_b,omitempty"`
	WitnessPeerId []byte                 `protobuf:"bytes,4,opt,name=witness_peer_id,json=witnessPeerId,proto3" json:"witness_peer_id,omitempty"`
	// Ed25519 signature over SHA-256(canonical_bytes) of this message with
	// witness_signature zeroed.
	WitnessSignature []byte `protobuf:"bytes,5,opt,name=witness_signature,json=witnessSignature,proto3" json:"witness_signature,omitempty"`
	TimestampUnixNs  int64  `protobuf:"varint,6,opt,name=timestamp_unix_ns,json=timestampUnixNs,proto3" json:"timestamp_unix_ns,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EquivocationAlert) Reset() {
	*x = EquivocationAlert{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquivocationAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquivocationAlert) ProtoMessage() {}

func (x *EquivocationAlert) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquivocationAlert.ProtoReflect.Descriptor instead.
func (*EquivocationAlert) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *EquivocationAlert) GetPeerId() []byte {
	if x != nil {
		return x.PeerId
	}
	return nil
}

func (x *EquivocationAlert) GetHeadA() *LogHead {
	if x != nil {
		return x.HeadA
	}
	return nil
}

func (x *EquivocationAlert) GetHeadB() *LogHead {
	if x != nil {
		return x.HeadB
	}
	return nil
}

func (x *EquivocationAlert) GetWitnessPeerId() []byte {
	if x != nil {
		return x.WitnessPeerId
	}
	return nil
}

func (x *EquivocationAlert) GetWitnessSignature() []byte {
	if x != nil {
		return x.WitnessSignature
	}
	return nil
}

func (x *EquivocationAlert) GetTimestampUnixNs() int64 {
	if x != nil {
		return x.TimestampUnixNs
	}
	return 0
}

// Tagged-union wrapper used by the ledger to handle either entry kind
// through a single Append / Verify path. The inner Rating or Comment
// carries its own prev_hash + signature; SignedEntry just routes by kind.
type SignedEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*SignedEntry_Rating
	//	*SignedEntry_Comment
	Body          isSignedEntry_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedEntry) Reset() {
	*x = SignedEntry{}
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEntry) ProtoMessage() {}

func (x *SignedEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agentfm_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEntry.ProtoReflect.Descriptor instead.
func (*SignedEntry) Descriptor() ([]byte, []int) {
	return file_agentfm_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *SignedEntry) GetBody() isSignedEntry_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *SignedEntry) GetRating() *Rating {
	if x != nil {
		if x, ok := x.Body.(*SignedEntry_Rating); ok {
			return x.Rating
		}
	}
	return nil
}

func (x *SignedEntry) GetComment() *Comment {
	if x != nil {
		if x, ok := x.Body.(*SignedEntry_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

type isSignedEntry_Body interface {
	isSignedEntry_Body()
}

type SignedEntry_Rating struct {
	Rating *Rating `protobuf:"bytes,1,opt,name=rating,proto3,oneof"`
}

type SignedEntry_Comment struct {
	Comment *Comment `protobuf:"bytes,2,opt,name=comment,proto3,oneof"`
}

func (*SignedEntry_Rating) isSignedEntry_Body() {}

func (*SignedEntry_Comment) isSignedEntry_Body() {}

var File_agentfm_ledger_v1_ledger_proto protoreflect.FileDescriptor

var file_agentfm_ledger_v1_ledger_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x22, 0x8f, 0x02, 0x0a, 0x06, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x22,
	0x0a, 0x0d, 0x72, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x61, 0x74, 0x65, 0x72, 0x50, 0x65, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x70, 0x65,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x73, 0x75, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e,
	0x69, 0x78, 0x4e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4a,
	0x04, 0x08, 0x09, 0x10, 0x10, 0x22, 0xa2, 0x02, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x61, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x72, 0x61, 0x74, 0x65, 0x72, 0x50,
	0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x74, 0x65, 0x78, 0x74, 0x43, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67,
	0x75, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64,
	0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x61,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x2a, 0x0a,
	0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f,
	0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x72, 0x65,
	0x76, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72,
	0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x4a, 0x04, 0x08, 0x09, 0x10, 0x10, 0x22, 0x58, 0x0a, 0x0a, 0x57, 0x69,
	0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x12, 0x26, 0x0a, 0x0f, 0x77, 0x69, 0x74, 0x6e,
	0x65, 0x73, 0x73, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x50, 0x65, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x4a, 0x04,
	0x08, 0x03, 0x10, 0x10, 0x22, 0x91, 0x02, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x48, 0x65, 0x61, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x65,
	0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x72,
	0x65, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72, 0x6f, 0x6f, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x40, 0x0a,
	0x0c, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53,
	0x69, 0x67, 0x52, 0x0b, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x6b, 0x6f, 0x72, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x6b, 0x6f, 0x72, 0x41, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x4a, 0x04, 0x08, 0x08, 0x10, 0x10, 0x22, 0xfe, 0x01, 0x0a, 0x0e, 0x49, 0x6e, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x12, 0x33, 0x0a, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x48, 0x00, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x74, 0x50,
	0x61, 0x74, 0x68, 0x12, 0x35, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67, 0x48, 0x65, 0x61,
	0x64, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x48, 0x65, 0x61, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x6e,
	0x74, 0x72, 0x79, 0x4a, 0x04, 0x08, 0x06, 0x10, 0x10, 0x22, 0x99, 0x02, 0x0a, 0x11, 0x45, 0x71,
	0x75, 0x69, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x5f, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x66, 0x6d, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67,
	0x48, 0x65, 0x61, 0x64, 0x52, 0x05, 0x68, 0x65, 0x61, 0x64, 0x41, 0x12, 0x31, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x5f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x6f, 0x67, 0x48, 0x65, 0x61, 0x64, 0x52, 0x05, 0x68, 0x65, 0x61, 0x64, 0x42, 0x12, 0x26,
	0x0a, 0x0f, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73,
	0x50, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73,
	0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x10, 0x77, 0x69, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x55, 0x6e, 0x69, 0x78, 0x4e, 0x73, 0x4a,
	0x04, 0x08, 0x07, 0x10, 0x10, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67,
	0x48, 0x00, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2e, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x10,
	0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x66, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_agentfm_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_agentfm_ledger_v1_ledger_proto_rawDescData = file_agentfm_ledger_v1_ledger_proto_rawDesc
)

func file_agentfm_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_agentfm_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_agentfm_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(file_agentfm_ledger_v1_ledger_proto_rawDescData)
	})
	return file_agentfm_ledger_v1_ledger_proto_rawDescData
}

var file_agentfm_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agentfm_ledger_v1_ledger_proto_goTypes = []any{
	(*Rating)(nil),            // 0: agentfm.ledger.v1.Rating
	(*Comment)(nil),           // 1: agentfm.ledger.v1.Comment
	(*WitnessSig)(nil),        // 2: agentfm.ledger.v1.WitnessSig
	(*LogHead)(nil),           // 3: agentfm.ledger.v1.LogHead
	(*InclusionProof)(nil),    // 4: agentfm.ledger.v1.InclusionProof
	(*EquivocationAlert)(nil), // 5: agentfm.ledger.v1.EquivocationAlert
	(*SignedEntry)(nil),       // 6: agentfm.ledger.v1.SignedEntry
}
var file_agentfm_ledger_v1_ledger_proto_depIdxs = []int32{
	2, // 0: agentfm.ledger.v1.LogHead.witness_sigs:type_name -> agentfm.ledger.v1.WitnessSig
	0, // 1: agentfm.ledger.v1.InclusionProof.rating:type_name -> agentfm.ledger.v1.Rating
	1, // 2: agentfm.ledger.v1.InclusionProof.comment:type_name -> agentfm.ledger.v1.Comment
	3, // 3: agentfm.ledger.v1.InclusionProof.log_head:type_name -> agentfm.ledger.v1.LogHead
	3, // 4: agentfm.ledger.v1.EquivocationAlert.head_a:type_name -> agentfm.ledger.v1.LogHead
	3, // 5: agentfm.ledger.v1.EquivocationAlert.head_b:type_name -> agentfm.ledger.v1.LogHead
	0, // 6: agentfm.ledger.v1.SignedEntry.rating:type_name -> agentfm.ledger.v1.Rating
	1, // 7: agentfm.ledger.v1.SignedEntry.comment:type_name -> agentfm.ledger.v1.Comment
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_agentfm_ledger_v1_ledger_proto_init() }
func file_agentfm_ledger_v1_ledger_proto_init() {
	if File_agentfm_ledger_v1_ledger_proto != nil {
		return
	}
	file_agentfm_ledger_v1_ledger_proto_msgTypes[4].OneofWrappers = []any{
		(*InclusionProof_Rating)(nil),
		(*InclusionProof_Comment)(nil),
	}
	file_agentfm_ledger_v1_ledger_proto_msgTypes[6].OneofWrappers = []any{
		(*SignedEntry_Rating)(nil),
		(*SignedEntry_Comment)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_agentfm_ledger_v1_ledger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agentfm_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_agentfm_ledger_v1_ledger_proto_depIdxs,
		MessageInfos:      file_agentfm_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_agentfm_ledger_v1_ledger_proto = out.File
	file_agentfm_ledger_v1_ledger_proto_rawDesc = nil
	file_agentfm_ledger_v1_ledger_proto_goTypes = nil
	file_agentfm_ledger_v1_ledger_proto_depIdxs = nil
}
